apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-s3.fullname" . }}
  labels:
    {{- include "nginx-s3.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nginx-s3.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nginx-s3.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nginx-s3.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          {{- with .Values.nginx.s3.bucketName }}
          - name: S3_BUCKET_NAME
            value: "{{ . }}"
          {{ end }}
          {{- with .Values.nginx.s3.accessKey }}
          - name: AWS_ACCESS_KEY_ID
            value: "{{ . }}"
          {{ end }}
          {{- with .Values.nginx.s3.secretKey }}
          - name: AWS_SECRET_ACCESS_KEY
            value: "{{ . }}"
          {{ end }}
          {{- with .Values.nginx.s3.server.host }}
          - name: S3_SERVER
            value: "{{ . }}"
          {{ end }}
          {{- with .Values.nginx.s3.server.port }}
          - name: S3_SERVER_PORT
            value: "{{ . }}"
          {{ end }}
          {{- with .Values.nginx.s3.server.proto }}
          - name: S3_SERVER_PROTO
            value: "{{ . }}"
          {{ end }}
          {{- with .Values.nginx.s3.awsregion }}
          - name: AWS_REGION
            value: "{{ . }}"
          {{ end }}
          {{- with .Values.nginx.s3.region }}
          - name: S3_REGION
            value: "{{ . }}"
          {{ end }}
          {{- with .Values.nginx.s3.style }}
          - name: S3_STYLE
            value: "{{ . }}"
          {{ end }}
          {{- with .Values.nginx.s3.debug }}
          - name: DEBUG
            value: "{{ . }}"
          {{ end }}
          - name: ALLOW_DIRECTORY_LIST
            value: "{{ .Values.nginx.s3.allowDirectoryListing }}"
          {{- with .Values.nginx.s3.provideIndexPage }}
          - name: PROVIDE_INDEX_PAGE
            value: "{{ . }}"
          {{ end }}
          {{- with .Values.nginx.s3.awsSigsVersion }}
          - name: AWS_SIGS_VERSION
            value: "{{ . }}"
          {{ end }}
          {{- with .Values.nginx.extraEnvs }}
            {{ . | toYaml | nindent 10 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
